# mkdocs.yml
site_name: AgentEvolver
# site_url: https://<你的GitHub用户名>.github.io/<仓库名>/
# repo_url: https://github.com/<你的GitHub用户名>/<仓库名>
# repo_name: <你的GitHub用户名>/<仓库名>

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  icon: heroicons:rocket-launch # use the shadcn svg if not defined
  topbar_sections: false # NEW!
  katex_options: # optional
    macros: # example of macros
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: false 

plugins:
  - search:
      lang: [zh, en]   # 中文搜索更友好（安装了 jieba）
nav:
  - Welcome: index.md
  - Tutorial: 
      - Installation: tutorial/install.md
      - Configuration: tutorial/configuration.md
      - Quick Start: tutorial/quick_start.md
  - Guidelines: 
      - Environment Service: guidelines/env_service.md
      - Task Manager: guidelines/task_manager.md
      - Context Manager: guidelines/context_manager.md
      - Experience Manager: guidelines/exp_manager.md
      - Credit Manager: guidelines/credit_manager.md
  - API Reference:
      - API Reference: api/api_1.md


markdown_extensions:
  - admonition
  - codehilite